# Syncs docs/GenericCRMAssistant_SystemPrompt.txt to the All-in-One agent's
# ccai__System_Prompt__c field on the default org.
#
# Strategy (Jira V2-8418):
#   - For prompts that fit, bake into a one-shot anonymous-Apex update and
#     verify via System.debug round-trip.
#   - For prompts that exceed the 32 KB Apex anonymous-script limit, fall
#     back to a REST PATCH (sf api request rest) which has no such limit,
#     then verify via SOQL.
#
# Usage:  powershell -ExecutionPolicy Bypass -File scripts\SyncSystemPromptToOrg.ps1
# Override the agent Id with -AgentId if needed.

param(
    [string] $AgentId          = 'a0sJ9000001BSF5IAO',
    [string] $SystemPromptPath = 'docs\GenericCRMAssistant_SystemPrompt.txt',
    [string] $ApiVersion       = 'v66.0'
)

$ErrorActionPreference = 'Stop'

$root        = Split-Path -Parent $PSScriptRoot
$promptPath  = Join-Path $root $SystemPromptPath
$tempApex    = Join-Path $root 'scripts\_sync_sysprompt.apex'
$tempJson    = Join-Path $root 'scripts\_sync_body.json'

if (-not (Test-Path $promptPath)) { throw "System prompt file not found: $promptPath" }

# ----- Read prompt content -----------------------------------------------------
# Use ReadAllText so we get the file contents verbatim (no PSObject wrapping
# from PowerShell's pipeline).
$raw = [System.IO.File]::ReadAllText($promptPath)
$expectedChars = ($raw -replace "`r`n", "`n").Length

# ----- Build candidate Apex payload (will use only if it fits) ----------------
$escaped = $raw -replace '\\', '\\'
$escaped = $escaped -replace "'", "\'"
$escaped = $escaped -replace "`r`n", "`n"
$escaped = $escaped -replace "`r",   "`n"
$escaped = $escaped -replace "`n",   '\n'

$apex = @"
// Auto-generated by scripts\SyncSystemPromptToOrg.ps1 - DO NOT EDIT BY HAND
String SP = '$escaped';
ccai__AI_Agent__c agent = new ccai__AI_Agent__c(
    Id = '$AgentId',
    ccai__System_Prompt__c = SP
);
update agent;
ccai__AI_Agent__c verify = [
    SELECT ccai__System_Prompt__c FROM ccai__AI_Agent__c WHERE Id = '$AgentId' LIMIT 1
];
String stored      = verify.ccai__System_Prompt__c == null ? '' : verify.ccai__System_Prompt__c;
Integer storedLen  = stored.length();
String localTrim   = SP.endsWith('\n') ? SP.removeEnd('\n') : SP;
Integer trimmedLen = localTrim.length();
Boolean exact      = (storedLen == SP.length());
Boolean trimmed    = (storedLen == trimmedLen) && stored.equals(localTrim);
System.debug('SYSPROMPT_LOCAL_CHARS=' + SP.length());
System.debug('SYSPROMPT_STORED_CHARS=' + storedLen);
System.debug('SYSPROMPT_MATCH=' + (exact || trimmed));
System.debug('SYSPROMPT_MATCH_KIND=' + (exact ? 'exact' : (trimmed ? 'trim-trailing-newline' : 'mismatch')));
"@

[IO.File]::WriteAllText($tempApex, $apex, [Text.UTF8Encoding]::new($false))
$apexBytes = (Get-Item $tempApex).Length
$apexKb    = [Math]::Round($apexBytes / 1KB, 2)
Write-Host "Apex script size: $apexKb KB (limit 32 KB).  Prompt length: $expectedChars chars (LF-normalised)."

# ----- Decide path: Apex if it fits, otherwise REST PATCH ---------------------
$useRest = $apexBytes -gt 32000

Push-Location $root
$prevPref = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
try {
    if (-not $useRest) {
        Write-Host "`nMode: anonymous-Apex (sf apex run)."
        $relPath = Resolve-Path $tempApex -Relative
        $output  = (cmd /c "sf apex run --file `"$relPath`" 2>&1") | Out-String
        Write-Host $output

        $localChars  = if ($output -match 'SYSPROMPT_LOCAL_CHARS=(\d+)')  { [int]$Matches[1] } else { -1 }
        $storedChars = if ($output -match 'SYSPROMPT_STORED_CHARS=(\d+)') { [int]$Matches[1] } else { -1 }
        $match       = if ($output -match 'SYSPROMPT_MATCH=(true|false)') { $Matches[1] }      else { 'unknown' }
        $matchKind   = if ($output -match 'SYSPROMPT_MATCH_KIND=([\w-]+)') { $Matches[1] }      else { 'unknown' }
    } else {
        Write-Host "`nMode: REST PATCH (sf api request rest) - prompt exceeds 32 KB Apex anonymous-script limit."
        # Build JSON body with explicit string cast to avoid PSObject wrapping.
        $bodyObj = [pscustomobject]@{ ccai__System_Prompt__c = [string]$raw }
        $body    = $bodyObj | ConvertTo-Json -Compress -Depth 2
        [IO.File]::WriteAllText($tempJson, $body, [Text.UTF8Encoding]::new($false))

        $endpoint = "/services/data/$ApiVersion/sobjects/ccai__AI_Agent__c/$AgentId"
        $relJson  = Resolve-Path $tempJson -Relative
        $patchOut = (cmd /c "sf api request rest `"$endpoint`" --method PATCH --header `"Content-Type:application/json`" --body `"@$relJson`" 2>&1") | Out-String
        Write-Host $patchOut

        # PATCH returns 204 No Content on success (empty body, exit 0).
        if ($LASTEXITCODE -ne 0 -or $patchOut -match 'errorCode' -or $patchOut -match 'Error \(') {
            Write-Warning "REST PATCH failed - inspect output above."
            exit 1
        }

        # Verify by reading back via SOQL. sf CLI emits a "» Warning:" banner
        # on stderr which would corrupt JSON parsing if interleaved with
        # stdout — strip everything before the first '{' before parsing.
        $verifyOut  = (cmd /c "sf data query --query `"SELECT ccai__System_Prompt__c FROM ccai__AI_Agent__c WHERE Id = '$AgentId'`" --json 2>&1") | Out-String
        $braceIdx   = $verifyOut.IndexOf('{')
        $verifyJson = if ($braceIdx -ge 0) { $verifyOut.Substring($braceIdx) } else { $verifyOut }
        try {
            $verify = $verifyJson | ConvertFrom-Json
            $stored = [string]$verify.result.records[0].ccai__System_Prompt__c
        } catch {
            Write-Warning "Could not parse verification SOQL response."
            Write-Host $verifyOut
            exit 1
        }

        $localChars  = ($raw -replace "`r`n", "`n").Length
        $storedChars = $stored.Length

        # Content-level checks (preferred over char-count, which differs by
        # CRLF/LF and UTF-8 multi-byte handling between PS and Salesforce).
        $marker1 = $raw.Substring(0, [Math]::Min(60, $raw.Length))
        $marker2 = $raw.Substring([Math]::Max(0, $raw.Length - 60))
        $headOk  = $stored.Contains($marker1.TrimEnd("`r","`n"))
        $tailOk  = $stored.Contains($marker2.TrimEnd("`r","`n"))

        if ($headOk -and $tailOk) {
            $match     = 'true'
            $matchKind = 'rest-content-match'
        } else {
            $match     = 'false'
            $matchKind = 'rest-content-mismatch'
        }
    }
} finally {
    $ErrorActionPreference = $prevPref
    Pop-Location
}

Write-Host ""
Write-Host "RESULT:"
Write-Host "  local chars   = $localChars"
Write-Host "  stored chars  = $storedChars"
Write-Host "  match         = $match  ($matchKind)"

# Cleanup
if (Test-Path $tempApex) { Remove-Item $tempApex -Force }
if (Test-Path $tempJson) { Remove-Item $tempJson -Force }

if ($match -ne 'true') {
    Write-Warning "Sync verification did NOT match - inspect the output above."
    exit 1
}

Write-Host "`nDone. docs\GenericCRMAssistant_SystemPrompt.txt is now in sync with agent $AgentId."
